spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: demo-transaction
  datasource:
    url: jdbc:mysql://localhost:3306/open_learn_hub
    username: root
    password: boquang321
    driver-class-name: com.mysql.cj.jdbc.Driver
  server:
    port: 8080
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        security: DEBUG